# Generated by Django 3.2.17 on 2023-02-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
